"""
Spark application for generating propensity score matching (PSM) datasets.

Accepts pre-built target and comparator cohort parquets generated by the
synthetic_trial_nference allofus pipeline (du_timelines and no_du_timelines
cache files).  The cohorts already contain index_date and outcome columns.
This script unions the two arms, extracts EHR feature sequences from OMOP
parquet tables, and joins the cohort metadata for downstream model training.

Expected target cohort columns (du_timelines):
    person_id, medication_start_date, drug_ingredient_name,
    gender_concept_id, race_concept_id, age_at_index, age_group_at_index,
    observation_window, followup_window, longitudinal_duration,
    {outcome_label}_date, last_observed_date, event, exposed

Expected comparator cohort columns (no_du_timelines):
    person_id, index_date, drug_ingredient_name,
    gender_concept_id, race_concept_id, age_at_index, age_group_at_index,
    observation_window, followup_window, longitudinal_duration,
    {outcome_label}_date, last_observed_date, event, exposed

Binary label: target arm → label=1, comparator arm → label=0.

Treatment concept IDs (both arms) and their descendants are excluded from
patient sequences to prevent label leakage.
"""

import argparse
import logging
import os
import shutil
from typing import List, Optional

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window

from cehrbert_data.const.common import (
    CONCEPT,
    CONCEPT_ANCESTOR,
    PERSON,
    VISIT_OCCURRENCE,
)
from cehrbert_data.decorators import AttType
from cehrbert_data.utils.logging_utils import add_console_logging
from cehrbert_data.utils.spark_utils import (
    create_sequence_data_with_att,
    extract_ehr_records,
    preprocess_domain_table,
    validate_table_names,
)
from cehrbert_data.utils.vocab_utils import get_descendant_concept_ids

LOGGER = logging.getLogger(__name__)


def _get_exclusion_concepts(
    spark: SparkSession,
    concept_ids: List[int],
) -> Optional[DataFrame]:
    """Return a single-column DataFrame of concept IDs (and all descendants) to exclude."""
    if not concept_ids:
        return None
    base_df = spark.createDataFrame(
        [(int(c),) for c in concept_ids], ["standard_concept_id"]
    )
    descendant_df = get_descendant_concept_ids(spark, concept_ids).select(
        F.col("concept_id").alias("standard_concept_id")
    )
    return base_df.union(descendant_df).distinct()


def _create_observation_window_filter(
    observation_window: int,
    hold_off_window: int,
    is_unbounded: bool,
) -> "Column":
    if is_unbounded:
        return F.col("ehr.datetime") <= F.expr(
            f"cohort.index_date - INTERVAL {hold_off_window} DAYS + INTERVAL 0.1 SECOND"
        )
    return F.col("ehr.datetime").between(
        F.expr(f"cohort.index_date - INTERVAL {observation_window + hold_off_window} DAYS"),
        F.expr(f"cohort.index_date - INTERVAL {hold_off_window} DAYS + INTERVAL 0.1 SECOND"),
    )


def main(
    input_folder: str,
    output_folder: str,
    target_cohort_path: str,
    comparator_cohort_path: str,
    outcome_label: str,
    domain_table_list: List[str],
    observation_window: int = 365,
    hold_off_window: int = 0,
    att_type: AttType = AttType.DAY,
    inpatient_att_type: AttType = AttType.DAY,
    is_drug_roll_up_concept: bool = True,
    include_concept_list: bool = False,
    num_of_visits: int = 0,
    num_of_concepts: int = 0,
    patient_splits_folder: Optional[str] = None,
    cache_events: bool = False,
    is_observation_window_unbounded: bool = False,
    aggregate_by_hour: bool = True,
    refresh_measurement: bool = False,
    treatment_concept_ids: Optional[List[int]] = None,
):
    spark = (
        SparkSession.builder.appName("Generate PSM Training Data")
        .config("spark.sql.session.timeZone", "UTC")
        .getOrCreate()
    )

    LOGGER.info(
        f"input_folder: {input_folder}\n"
        f"output_folder: {output_folder}\n"
        f"target_cohort_path: {target_cohort_path}\n"
        f"comparator_cohort_path: {comparator_cohort_path}\n"
        f"outcome_label: {outcome_label}\n"
        f"domain_table_list: {domain_table_list}\n"
        f"observation_window: {observation_window}\n"
        f"hold_off_window: {hold_off_window}\n"
        f"att_type: {att_type}\n"
        f"inpatient_att_type: {inpatient_att_type}\n"
        f"is_drug_roll_up_concept: {is_drug_roll_up_concept}\n"


        f"include_concept_list: {include_concept_list}\n"
        f"num_of_visits: {num_of_visits}\n"
        f"num_of_concepts: {num_of_concepts}\n"

        f"cache_events: {cache_events}\n"
        f"is_observation_window_unbounded: {is_observation_window_unbounded}\n"
        f"aggregate_by_hour: {aggregate_by_hour}\n"
        f"refresh_measurement: {refresh_measurement}\n"
        f"treatment_concept_ids: {treatment_concept_ids}\n"
    )

    # Register concept tables as global temp views for descendant expansion
    for table_name in [CONCEPT, CONCEPT_ANCESTOR]:
        tbl = preprocess_domain_table(spark, input_folder, table_name)
        tbl.createOrReplaceGlobalTempView(table_name)

    # Load and normalise one arm of the cohort.
    # du_timelines (target) uses medication_start_date; no_du_timelines (comparator)
    # uses index_date.  Both use {outcome_label}_date for the outcome date column.
    def _load_cohort(path: str) -> DataFrame:
        df = spark.read.parquet(path)
        # Target arm: rename medication_start_date → index_date
        if "medication_start_date" in df.columns and "index_date" not in df.columns:
            df = df.withColumnRenamed("medication_start_date", "index_date")
        # Rename outcome date column: {outcome_label}_date → outcome_date
        outcome_date_col = f"{outcome_label}_date"
        if outcome_date_col in df.columns and "outcome_date" not in df.columns:
            df = df.withColumnRenamed(outcome_date_col, "outcome_date")
        return df

    target = _load_cohort(target_cohort_path).withColumn("label", F.lit(1))
    comparator = _load_cohort(comparator_cohort_path).withColumn("label", F.lit(0))
    cohort = target.unionByName(comparator, allowMissingColumns=True)

    # Cast index_date to date so interval arithmetic is consistent
    cohort = cohort.withColumn("index_date", F.col("index_date").cast("date"))

    # Assign a unique cohort_member_id per (person_id, index_date)
    cohort = cohort.withColumn(
        "cohort_member_id",
        F.dense_rank().over(Window.orderBy("person_id", "index_date")),
    )

    # If the same person+index_date appears in both arms (overlap), keep label=1
    dedup_rank = F.row_number().over(
        Window.partitionBy("person_id", "index_date").orderBy(F.desc("label"))
    )
    cohort = cohort.withColumn("_dedup", dedup_rank).where("_dedup = 1").drop("_dedup")


    # Build exclusion set for EHR sequences to prevent treatment concept leakage
    exclude_df = _get_exclusion_concepts(spark, treatment_concept_ids or [])

    # Extract raw EHR events for all patients in the cohort
    ehr_records = extract_ehr_records(
        spark=spark,
        input_folder=input_folder,
        domain_table_list=domain_table_list,
        include_visit_type=True,
        with_diagnosis_rollup=False,
        with_drug_rollup=is_drug_roll_up_concept,
        include_concept_list=include_concept_list,
        refresh_measurement=refresh_measurement,
        aggregate_by_hour=aggregate_by_hour,
    )

    # Remove treatment concepts so the sequence cannot trivially predict the label
    if exclude_df is not None:
        ehr_records = ehr_records.join(exclude_df, "standard_concept_id", "left_anti")

    if cache_events:
        events_dir = os.path.join(output_folder, "all_patient_events")
        ehr_records.write.mode("overwrite").parquet(events_dir)
        ehr_records = spark.read.parquet(events_dir)

    # Cross-join ehr records with cohort members so each index date gets its own copy
    ehr_records = (
        ehr_records.alias("ehr")
        .join(
            cohort.select("person_id", "cohort_member_id").alias("cohort"),
            F.col("ehr.person_id") == F.col("cohort.person_id"),
        )
        .select(
            [F.col("ehr." + c) for c in ehr_records.columns] + [F.col("cohort.cohort_member_id")]
        )
    )

    # Apply the observation window filter per cohort member
    window_filter = _create_observation_window_filter(
        observation_window, hold_off_window, is_observation_window_unbounded
    )
    cohort_ehr_records = (
        ehr_records.alias("ehr")
        .join(
            cohort.alias("cohort"),
            (F.col("ehr.person_id") == F.col("cohort.person_id"))
            & (F.col("ehr.cohort_member_id") == F.col("cohort.cohort_member_id")),
        )
        .where(window_filter)
        .select([F.col("ehr." + f) for f in ehr_records.schema.fieldNames()])
    )

    # Build visit_occurrence joined with patient demographics for the ATT decorator
    birthdate_udf = F.coalesce(
        "birth_datetime",
        F.concat("year_of_birth", F.lit("-01-01")).cast("timestamp"),
    )
    person = preprocess_domain_table(spark, input_folder, PERSON).select(
        "person_id",
        birthdate_udf.alias("birth_datetime"),
        "race_concept_id",
        "gender_concept_id",
    )
    visit_occurrence = preprocess_domain_table(spark, input_folder, VISIT_OCCURRENCE)
    visit_occurrence_person = (
        visit_occurrence.join(person, "person_id")
        .withColumn(
            "age",
            F.ceil(F.months_between(F.col("visit_start_date"), F.col("birth_datetime")) / F.lit(12)),
        )
        .drop("birth_datetime")
    )

    # Generate patient sequences with ATT tokens (demographics included)
    patient_sequence = create_sequence_data_with_att(
        cohort_ehr_records,
        visit_occurrence=visit_occurrence_person,
        include_visit_type=True,
        exclude_visit_tokens=False,
        att_type=att_type,
        inpatient_att_type=inpatient_att_type,
        exclude_demographic=False,
        use_age_group=False,
        include_inpatient_hour_token=False,
        spark=spark if cache_events else None,
        persistence_folder=output_folder if cache_events else None,
        cohort_index=cohort.select("person_id", "cohort_member_id", "index_date"),
    )

    if num_of_visits > 0:
        patient_sequence = patient_sequence.where(F.col("num_of_visits") >= num_of_visits)
    if num_of_concepts > 0:
        patient_sequence = patient_sequence.where(F.col("num_of_concepts") >= num_of_concepts)

    # Join the full cohort metadata (label, index_date, outcome columns, demographics)
    dataset = patient_sequence.join(cohort, ["person_id", "cohort_member_id"])

    # Write output, splitting by train/test if patient splits are available
    if patient_splits_folder:
        patient_splits = spark.read.parquet(patient_splits_folder)
        temp_folder = os.path.join(output_folder, "temp")
        dataset.join(
            patient_splits.select("person_id", "split"), "person_id"
        ).write.mode("overwrite").parquet(temp_folder)
        dataset = spark.read.parquet(temp_folder)
        dataset.where('split = "train"').write.mode("overwrite").parquet(
            os.path.join(output_folder, "train")
        )
        dataset.where('split = "test"').write.mode("overwrite").parquet(
            os.path.join(output_folder, "test")
        )
        shutil.rmtree(temp_folder)
    else:
        dataset.orderBy("person_id", "index_date").write.mode("overwrite").parquet(
            os.path.join(output_folder, "data")
        )


def create_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a propensity score matching dataset from OMOP CDM data. "
            "Reads a pre-built cohort parquet (from the allofus pipeline) and "
            "extracts EHR feature sequences from OMOP parquet tables."
        )
    )
    parser.add_argument(
        "--input_folder",
        dest="input_folder",
        required=True,
        help="Path to OMOP parquet tables",
    )
    parser.add_argument(
        "--output_folder",
        dest="output_folder",
        required=True,
        help="Output path for the PSM dataset",
    )
    parser.add_argument(
        "--target_cohort_path",
        dest="target_cohort_path",
        required=True,
        help=(
            "Path to the target (exposed) cohort parquet (allofus pipeline output). "
            "Must contain: person_id, index_date, event, outcome_date, "
            "age_at_index (or age), gender_concept_id, race_concept_id."
        ),
    )
    parser.add_argument(
        "--comparator_cohort_path",
        dest="comparator_cohort_path",
        required=True,
        help=(
            "Path to the comparator (control) cohort parquet (allofus no_du_timelines). "
            "Must contain: person_id, index_date, {outcome_label}_date, event, "
            "age_at_index, gender_concept_id, race_concept_id."
        ),
    )
    parser.add_argument(
        "--outcome_label",
        dest="outcome_label",
        required=True,
        help=(
            "Primary outcome label from the allofus YAML config (e.g. 'stroke'). "
            "Used to locate the outcome date column '{outcome_label}_date' in both "
            "cohort parquets and rename it to 'outcome_date'."
        ),
    )
    parser.add_argument(
        "--domain_table_list",
        dest="domain_table_list",
        nargs="+",
        required=True,
        type=validate_table_names,
        help="OMOP domain tables to include for feature extraction",
    )
    parser.add_argument(
        "--treatment_concept_ids",
        dest="treatment_concept_ids",
        nargs="+",
        type=int,
        default=None,
        help=(
            "Ingredient concept IDs for both treatment arms (target + comparator). "
            "These and all their descendants are excluded from EHR sequences to "
            "prevent label leakage."
        ),
    )
    parser.add_argument(
        "--observation_window",
        dest="observation_window",
        type=int,
        default=365,
        help="Lookback window in days before index_date for feature extraction",
    )
    parser.add_argument(
        "--hold_off_window",
        dest="hold_off_window",
        type=int,
        default=0,
        help="Gap in days between the end of the observation window and index_date",
    )
    parser.add_argument(
        "--is_observation_window_unbounded",
        dest="is_observation_window_unbounded",
        action="store_true",
        help="Use all available history rather than a fixed observation window",
    )
    parser.add_argument(
        "--att_type",
        dest="att_type",
        choices=[e.value for e in AttType],
        default=AttType.DAY.value,
        help="ATT token strategy for time gaps between visits",
    )
    parser.add_argument(
        "--inpatient_att_type",
        dest="inpatient_att_type",
        choices=[e.value for e in AttType],
        default=AttType.DAY.value,
        help="ATT token strategy for time gaps within inpatient visits",
    )
    parser.add_argument(
        "--is_drug_roll_up_concept",
        dest="is_drug_roll_up_concept",
        action="store_true",
        help="Roll up drug concepts to ingredient level",
    )
    parser.add_argument(
        "--include_concept_list",
        dest="include_concept_list",
        action="store_true",
        help="Filter out low-frequency concepts using the qualified concept list",
    )
    parser.add_argument(
        "--num_of_visits",
        dest="num_of_visits",
        type=int,
        default=0,
        help="Minimum number of visits required to include a patient",
    )
    parser.add_argument(
        "--num_of_concepts",
        dest="num_of_concepts",
        type=int,
        default=0,
        help="Minimum number of concepts required to include a patient",
    )
    parser.add_argument(
        "--patient_splits_folder",
        dest="patient_splits_folder",
        default=None,
        help="Path to patient splits parquet for train/test partitioning",
    )
    parser.add_argument(
        "--cache_events",
        dest="cache_events",
        action="store_true",
        help="Persist intermediate event DataFrames to disk",
    )
    parser.add_argument(
        "--aggregate_by_hour",
        dest="aggregate_by_hour",
        action="store_true",
        help="Aggregate numeric measurements by hour within a visit",
    )
    parser.add_argument(
        "--refresh_measurement",
        dest="refresh_measurement",
        action="store_true",
        help="Re-process measurement binning from scratch",
    )
    return parser


if __name__ == "__main__":
    ARGS = create_argparser().parse_args()
    add_console_logging()
    main(
        input_folder=ARGS.input_folder,
        output_folder=ARGS.output_folder,
        target_cohort_path=ARGS.target_cohort_path,
        comparator_cohort_path=ARGS.comparator_cohort_path,
        outcome_label=ARGS.outcome_label,
        domain_table_list=ARGS.domain_table_list,
        observation_window=ARGS.observation_window,
        hold_off_window=ARGS.hold_off_window,
        att_type=AttType(ARGS.att_type),
        inpatient_att_type=AttType(ARGS.inpatient_att_type),
        is_drug_roll_up_concept=ARGS.is_drug_roll_up_concept,
        include_concept_list=ARGS.include_concept_list,
        num_of_visits=ARGS.num_of_visits,
        num_of_concepts=ARGS.num_of_concepts,
        patient_splits_folder=ARGS.patient_splits_folder,
        cache_events=ARGS.cache_events,
        is_observation_window_unbounded=ARGS.is_observation_window_unbounded,
        aggregate_by_hour=ARGS.aggregate_by_hour,
        refresh_measurement=ARGS.refresh_measurement,
        treatment_concept_ids=ARGS.treatment_concept_ids,
    )
