PERSON = "person"
VISIT_OCCURRENCE = "visit_occurrence"
CONDITION_OCCURRENCE = "condition_occurrence"
PROCEDURE_OCCURRENCE = "procedure_occurrence"
DRUG_EXPOSURE = "drug_exposure"
DEVICE_EXPOSURE = "device_exposure"
OBSERVATION = "observation"
MEASUREMENT = "measurement"
CATEGORICAL_MEASUREMENT = "categorical_measurement"
OBSERVATION_PERIOD = "observation_period"
DEATH = "death"
CDM_TABLES = [
    PERSON,
    VISIT_OCCURRENCE,
    CONDITION_OCCURRENCE,
    PROCEDURE_OCCURRENCE,
    DRUG_EXPOSURE,
    DEVICE_EXPOSURE,
    OBSERVATION,
    MEASUREMENT,
    CATEGORICAL_MEASUREMENT,
    OBSERVATION_PERIOD,
    DEATH,
]
REQUIRED_MEASUREMENT = "required_measurement"
UNKNOWN_CONCEPT = "[UNKNOWN]"
NA = "N/A"
CONCEPT = "concept"
CONCEPT_ANCESTOR = "concept_ancestor"
MEASUREMENT_QUESTION_PREFIX = "Question:"
MEASUREMENT_ANSWER_PREFIX = "Answer:"
